### ISSUE TITLE
MPCaaS Demo 

### ISSUE THREAD

**Issue by LaRiffle** [multiparty/jiff#177]
Hi, I'm trying to play with the demo: https://github.com/multiparty/jiff/tree/master/demos/mpc-as-a-service
I observe a strange behaviour: I can connect to http://localhost:8080/demos/mpc-as-a-service/client.html but the second section "Sum Numbers under MPC as a service" remains un-clickable even if I open several tabs :/

Do you have any hints of what I'm missing here?
Thanks!

**Comment by p-flock** [comment]
Hi! 
This demo is a bit confusing because of how many parties are involved. 
My intuition is that you have likely run the server and the input parties, but not run any of the compute parties.
Based on the config file in the demo, by default there are 3 compute parties required (not including the server) these are run like this:
```sh
node demos/mpc-as-a-service/compute-party.js
```
and 3 input parties, which are run in the browser.

It is a bit simpler to run on one machine if you change the config to require less parties, for example you could set it up to only require 2 compute parties and 2 input parties:
```
{
  "party_count": 4,
  "compute_parties": [1, 2],
  "input_parties": [3, 4]
}
```

Please update me if you are still having trouble or run into some other issue

**Comment by LaRiffle** [comment]
Hey thanks for the explanation!
One thing I didn't get also was to provide the **same** computation ID (I thought it was a client id and had to be unique)

It works now thank you! I'll make a PR to clarify the demo if this is relevant
