### ISSUE TITLE
Opening shares to non-holders

### ISSUE THREAD

**Issue by mikeazo** [multiparty/jiff#190]
With #15, it is possible to share some values with a subset. Is there an easy way to open a shared value to all parties or some (possibly disjoint) set of parties?

If so, how?

Here is a simple example:
1. Parties 1-3 compute the sum of their input values
2. Parties 1-3 wish to open the result to parties 1-6

I cannot figure out how to do this. The only way I can do it right now is to have the parties call reshare `jiff_instance.reshare(intermediate, null, null, [1,2,3])`, then call open. Can I skip the reshare step somehow?

**Comment by KinanBab** [comment]
Yes, you can do this with something like the below:

For parties 1-3, since they possess the secret share object, they can just call open, specifying the receiving parties.
```javascript
  <jiff_instance>.open(share, [1, 2, 3, 4, 5, 6]); // you can use share.open too
```

Parties 4-6 do not possess a share of this output, so they cannot call open, and must instead call a receive_open.
```javascript
<jiff_instance>.receive_open([1, 2, 3], [1, 2, 3, 4, 5, 6]);
```

Note that if the share was using some custom threshold or is in a custom field (Zp), these must be provided to receive_open as well.

It is up to you and your use case how to choose to split the code between the parties. If the differences in code between 1-3 and 4-6 is small, you can keep a single unified code file(s) for both subsets, and use something like `if ([1, 2, 3].indexOf(jiff_instance.id) > -1)` to put custom code for a subset.

If the code is very different, you can choose to separate the code files completely (with maybe some common code that is in a module used by both subsets). JIFF should be able to automatically figure out which receive_open in the second subset's code belong to which open in the first subset code, even when there are many such combinations.

https://multiparty.org/jiff/docs/jsdoc/module-jiff-client-JIFFClient.html#open
https://multiparty.org/jiff/docs/jsdoc/module-jiff-client-JIFFClient.html#receive_open

**Comment by KinanBab** [comment]
Note that using open/receive_open directly instead of reshare -> open is more efficient. It saves up a round of communication.

**Comment by mikeazo** [comment]
@KinanBab Thanks, that great! I'll get that working in my code. I was hoping this was possible since I knew it was more efficient.
