### ISSUE TITLE
SecretShare - Resolve Promise to Value

### ISSUE THREAD

**Issue by palladionIT** [multiparty/jiff#196]
Hello,
First of thanks for all your hard work I really appreciate it. I wanted to ask you about a feature or maybe about an approach on how to handle and store secret shares. I also looked through the web-mpc repository to understand how it is implemented there. However, it seems that this is a little overkill for what I want to do. 

**Goal**:
I want flexibility to store the secret shares at the compute parties to reuse them for iterative computations without resending from the client.

**My question**:
How can I access the value in a SecretShare? Specifically, what is the recommended way to resolve the promise and access the value of it?

**Ideas I had**:

1. Use the start_barrier and end_barrier to ensure they are resolved.
2. Call .then or even Promise.all myself on all the share promises.
3. Implement something funky similar to web-mpc where (if I understand correctly) the full messages that are to be sent are saved. (Although I think the use case there is a little different.)

My intuition would tell me that the best way is to use 1) but I wanted to ask you as the creators of the library if there is a better way or I have missed something.
Once again, thanks for making such an awesome and easy to use library!

**Comment by KinanBab** [comment]
Hi, This is a good question.

The web-mpc repository is a bit over the top when it comes to this, because of some extraneous requirements enforced on us by a variety of factors. I doubt that the same circumstances would apply to all but a few other applications.

A secret share in JIFF consists essentially of these components:
1. a share value: essentially a random number that when combined with other shares gives back the secret, in case where a share is still being computed the value will be a promise as you note.
2. a threshold: by default, this would be the same as the number of parties holding the share.
3. an array containing party ids that hold corresponding shares: traditionally all the parties.
4. Zp: the prime field that the computation happens under.

All these 4 components are needed to define the share, and indeed the secret share constructor expects them all as parameters. However, you probably do not need to store all of them (although you need to provide them explicity to the constructor).

The threshold, holders, and Zp are in most cases fixed. So in reality, what you need to store is only the value. When you want to re-use the stored share, you will need to call the constructor, pass in the stored value, the remaining fixed parameters, and you will get an identical resulting share that you can use for more computation.

The ideas you had all are good, I think 1 and 2 are probably the better approaches.

Note that (1) will wait for all the promises that are created within a barrier, this may include promises belonging to shares or operations that you do not wish to store.

Option (2) is pretty simple to read and understand, and I personally like it. Note that calling .then() directly is not always safe, since the value may already have been computed and is not a promise, so you should check for that first. Promise.all() is safe to use on promises or values or combination, so it should be alright.

Best

**Comment by KinanBab** [comment]
Feel free to close the issue if this answers your question fully, or follow up with any additional concerns

**Comment by palladionIT** [comment]
Hello,
Thank you very much for your quite elaborate answer! It helped a lot. I think I slowly start to grasp some of the internals of the library and I am also getting more comfortable with the SecretShares.

I wanted to briefly report on something that might be a bug (or more probable my lack of knowledge) in the barrier mechanism. When I collect the promises from the open operation and then run Promise.all() on them, all promises are resolved and I get the correct values. However, when I use the barriers often none and sometimes only one of the promises is resolved. My guess is that the promises collected in the barrier are not the same is the ones that will finally be returned by the open() call. I checked it and they seem not be the same promises. 
Maybe the issue is that in open.js line 100 the promise that is saved during the refresh of the shares (open.js line 74; protocol.js line 21 and share.js line 57) is wrapped in another promise!? I am by far not versed enough to understand the promise/deferred chains you built so take this analysis with a heap of salt. 

To give more information here is code that works:
```
    let results = [];
    pairwise_processing((p1, p2) => {
        let tmp = jiff_instance.open(matches[p1][p2], all_parties);
        matches[p1][p2] = tmp;
        results.push(tmp);
    });

    let tmp = Promise.all(results);

    tmp.then((final) => {
        console.log("done.");
        jiff_instance.disconnect(true, true);
    }).catch(err => {
        alert(err)
    });
```

and code that does **not** work:

```
    // Start Synchronization Block
    jiff_instance.start_barrier();

    pairwise_processing((p1, p2) => {
        let tmp = jiff_instance.open(matches[p1][p2], all_parties);
        matches[p1][p2] = tmp;
    });

    // End Synchronization Block
    let prom = jiff_instance.end_barrier()

    prom.then((data) => {
        console.log("done.");
        jiff_instance.disconnect(true, true);
    });
```
If this is a misunderstanding on my part and you find some time point out what I did wrong, I would would appreciate it.
Thank you for all the time that you take with my issues!

**Comment by Ra1issa** [comment]
Hello, sorry for the late reply, we had a crazy end of semester crunch.

You are right in what you are reporting. The barrier is not meant to return the values of the promises, only to "resolve" when all the promises and other internal asynchronous operations are done. It is only meant as a mechanism that provides developers with a signal to indicate that a code block/barrier has been finally executed.

The reason we do it this way is that there are many internal promises that are created by operations in JIFF, they are not exposed to the user (unlike the .open() which exposes its promise directly). It was not clear what standard we should set: should the barrier reveal the values of all these promises? or only certain ones that are exposed? if it is the later, how can we even distinguish between completely external and other potentially internal promises in a clean and efficient way? We decided to avoid this issue by making no guarantees about the values it reveals.

If this is a useful feature, we could modify the structure of the barriers to resolve with the values for some reasonable standard. Otherwise, we will make this limitation explicit in the documentation for the end_barrier function.
