### ISSUE TITLE
File serving for demos uses incorrect path

### ISSUE THREAD

**Issue by LaurenSpiegel** [multiparty/jiff#89]
Hi,

I don't know how running the demos with the current readme instructions and the current code is working for others. In the demos/demoName/server.js file, I had to replace: 

```javascript
app.use("/demos", express.static("demos"));
app.use("/lib", express.static("lib"));
app.use("/lib/ext", express.static("lib/ext"));
```
with:

```javascript
app.use("/demos/sum", express.static(__dirname));
```

**Comment by KinanBab** [comment]
Hi,

it depends on the directory from which you run the server. We built the demos assuming that people will run the server from the root directory of the project, i.e with something like this:

```bash
:~/Path/to/jiff$ node index.js demos/<demo-name>/server.js
:~/Path/to/jiff$ node demos/<demo-name>/server.js   # (same effect as above)
```
In that case, you will have to go to localhost:8080/demos/<demo-name>/client.html or run party.js regularly.

Your snippet uses _dirname which is an absolute path, so this gets rid of the issue of having to run the server from the root directory and allows it to be run from any directory.

@842Mono We should look into incorporating this into the servers for the demos (and the template), so that it is easier to run the demos. We must make sure all routes are working in a path-independent way including lib and lib/ext

**Comment by LaurenSpiegel** [comment]
Hi,

Thanks for the response. I had this problem running from the root of the project. Changing to use __dirname works. Just wanted to pass that along in case it will help others.
